### ISSUE TITLE
場地未設停用日期導致的錯誤

### ISSUE THREAD

**Issue by geek01** [tnjaile/jill_booking#1]
未設停用日期時，會以0000-00-00為預設值寫入，但在資料表jbi_end欄位是允許NULL的，這樣sql語法使用IS NULL判斷時，0000-00-00或0或空值，不會被判定為NULL，因此產生錯誤。
翻查mysql.sql修改歷史資料，
原本jbi_end欄位由NOT NULL改為NULL時，相關sql語法沒有配合修正 ，
可能要改回NOT NULL或修正sql語法，將空日期以NULL寫入，或不使用IS NULL判斷

**Comment by tnjaile** [comment]
感謝指教，我真的沒注意。
已在資料庫修正
jbi_end欄位NOT NULL
